### ISSUE TITLE
HTML edition posted to niap webpage?

### ISSUE THREAD

**Issue by shawndwells** [commoncriteria/virtualization#1]
HTML edition available through github (https://commoncriteria.github.io/pp/virtualization/virtualization-release.html) but not on NIAP webpage.

Can HTML edition be posted to compliment https://www.niap-ccevs.org/MMO/PP/pp_base_virtualization_v1.0.pdf ?

**Comment by robertmclemons** [comment]
The HTML version will be available for version 1.1 of the PP and both the client and server PP modules once the update is complete. Hopefully in Feb 2021.
