### ISSUE TITLE
Typos in Base PP

### ISSUE THREAD

**Issue by mclearn** [commoncriteria/virtualization#71]
Hi folks.  I've done a quick scrub for typos in the PP based on the published draft at https://commoncriteria.github.io/pp/virtualization/virtualization-release.html:

- FTA_TAB.1.1, the word "specifiedad" 
- Table 4 for row O.PLATFORM_INTEGRITY (and FPT_DVD_EXT.1), the word "onfigured"
- Appendix D, table 9, FAU_GEN.1 has "Audit Data Generatio"
- Appendix H, rule 16 has "selectedin"
- Appendix H has the word "statisfies"

**Comment by robertmclemons** [comment]
Thanks Greg. All typos fixed or pushed along to their source.
